---
authors:
  - Aubin Bibkouo (https://github.com/abikouo)
  - Jill Rouleau (https://github.com/jillr)
description: Amazon AWS roles and playbooks for Ansible.
documentation: ''
homepage: ''
issues: https://github.com/ansible-collections/cloud.aws_roles/issues
license_file: LICENSE
namespace: cloud
name: aws_roles
readme: README.md
repository: https://github.com/ansible-collections/cloud.aws_roles
tags:
  - amazon
  - aws
  - cloud
  - infrastructure
  - cluster
version: 0.1.0
build_ignore:
  - .DS_Store
  - '*.tar.gz'
