---
authors:
  - Ansible (https://github.com/ansible)
description: Amazon AWS roles and playbooks for Ansible.
documentation: ''
homepage: ''
issues: https://github.com/ansible-collections/cloud.aws_ops/issues
license_file: LICENSE
namespace: cloud
name: aws_ops
readme: README.md
repository: https://github.com/ansible-collections/cloud.aws_ops
tags:
  - amazon
  - aws
  - cloud
  - infrastructure
  - cluster
version: 1.0.0
build_ignore:
  - .DS_Store
  - '*.tar.gz'
