---
- name: Run 'create_global_cluster_with_rds_cluster' role
  module_defaults:
    group/aws: "{{ aws_setup_credentials__output }}"

  block: 
    # Create Aurora glboal DB cluster
    - name: Create Aurora global DB cluster
      amazon.cloud.rds_global_cluster:
        global_cluster_identifier: "{{ global_cluster_identifier }}"
        engine: "{{ engine }}"
        region: "{{ region_primary }}"

    # Create primary RDS cluster and instance
    - name: Create primary RDS cluster that connects with global db
      amazon.aws.rds_cluster:
        cluster_id: "{{ cluster_id }}"
        engine: "{{ engine }}"
        engine_mode: provisioned
        username: "{{ username }}"
        password: "{{ password }}"
        region: "{{ region_primary }}"
        db_subnet_group_name: "{{ db_subnet_group_name | default(omit) }}"
        global_cluster_identifier: "{{ global_cluster_identifier }}"
      register: primary_cluster
    
    - name: Create a RDS instance that connects with primary RDS cluster
      amazon.aws.rds_instance:
        cluster_id: "{{ cluster_id }}"
        db_instance_identifier: "{{ instance_id }}"
        engine: "{{ engine }}"
        db_instance_class: "{{ db_instance_class }}"
      
    
    - name: Create a RDS instance that connects with primary RDS cluster
      amazon.aws.rds_instance:
        cluster_id: "{{ cluster_id }}"
        db_instance_identifier: "{{ instance_id }}-two"
        engine: "{{ engine }}"
        db_instance_class: "{{ db_instance_class }}"

    # Replicating primary cluster and instance
    - name: Create primary RDS cluster that connects with global db
      amazon.aws.rds_cluster:
        cluster_id: "{{ cluster_id }}-replica"
        engine: "{{ engine }}"
        engine_mode: provisioned
        username: "{{ username }}"
        password: "{{ password }}"
        region: "{{ region_secondary }}"
        global_cluster_identifier: "{{ global_cluster_identifier }}"

