---
# Obtaining all the source bucket objects
- name: Obtaining all the source bucket objects
  amazon.aws.s3_object:
    bucket: "{{ moving_buckets_src }}"
    mode: list
  register: bucket_src_info

# Moving objects between buckets
- name: Copy an object already stored in another bucket
  amazon.aws.s3_object:
    bucket: "{{ moving_bucket_dest }}"
    object: "{{ item }}"
    mode: copy
    copy_src:
        bucket: "{{ moving_buckets_src }}"
        object: "{{ item }}"
  loop: "{{ bucket_src_info.s3_keys }}"

- name: Delete the source bucket objects
  amazon.aws.s3_object:
    bucket: "{{ moving_buckets_src }}"
    object: "{{ item }}"
    mode: delobj 
  loop: "{{ bucket_src_info.s3_keys }}"