---
- name: Run 'moving_object_between_buckets' role
  module_defaults:
    group/aws: "{{ aws_setup_credentials__output }}"

  block:
    # Checking required variables
    - name: Fail when 'source_bucket' is undefined
      ansible.builtin.fail:
        msg: source bucket should be defined as source_bucket
      when: source_bucket is undefined

    - name: Fail when 'dest_bucket' is undefined
      ansible.builtin.fail:
        msg: destination bucket should be defined as dest_bucket
      when: dest_bucket is undefined

    # Obtaining specifc or all the source bucket objects
    - name: Obtaining specifc or all the source bucket objects
      amazon.aws.s3_object:
        bucket: "{{ source_bucket }}"
        mode: list
        prefix: "{{ key_prefix | default('') }}"
      register: source_bucket_info

    # Transferring objects from source bucket to destination bucket
    - name: Moving objects between source bucket to destination bucket
      amazon.aws.s3_object:
        bucket: "{{ dest_bucket }}"
        object: "{{ item }}"
        mode: copy
        copy_src:
            bucket: "{{ source_bucket }}"
            object: "{{ item }}"
      loop: "{{ source_bucket_info.s3_keys }}"

    - name: Delete the source bucket objects
      amazon.aws.s3_object:
        bucket: "{{ source_bucket }}"
        object: "{{ item }}"
        mode: delobj 
      loop: "{{ source_bucket_info.s3_keys }}"
    
    # Delete source s3 bucket when empty
    - name: Obtaining all the source bucket objects
      amazon.aws.s3_object:
        bucket: "{{ source_bucket }}"
        mode: list
      when: delete_empty_source_bucket is defined and delete_empty_source_bucket
      register: source_bucket_info

    - name: Fail when the source s3 bucket is not empty and delete_empty_source_bucket is true
      ansible.builtin.fail:
        msg: The source must be emptied before it can be deleted.
      when: delete_empty_source_bucket is defined and delete_empty_source_bucket and source_bucket_info.s3_keys

    - name: Delete source s3 bucket when empty
      amazon.aws.s3_bucket:
        name: "{{ source_bucket }}"
        state: absent
      when: "{{ delete_empty_source_bucket | default(false) }}"