---
- name: Run 'moving_object_between_buckets' role
  module_defaults:
    group/aws: "{{ aws_setup_credentials__output }}"

  block:
    # Obtaining specifc or all the source bucket objects
    - name: Obtaining all the source bucket objects
      amazon.aws.s3_object:
        bucket: "{{ source_bucket }}"
        mode: list
        prefix: "{{ source_bucket_object_prefix | default('') }}"
      register: source_bucket_info

    # Transferring objects from source bucket to destination bucket
    - name: Moving objects between source bucket to destination bucket
      amazon.aws.s3_object:
        bucket: "{{ dest_bucket }}"
        object: "{{ item }}"
        mode: copy
        copy_src:
            bucket: "{{ source_bucket }}"
            object: "{{ item }}"
      loop: "{{ source_bucket_info.s3_keys }}"

    - name: Delete the source bucket objects
      amazon.aws.s3_object:
        bucket: "{{ source_bucket }}"
        object: "{{ item }}"
        mode: delobj 
      loop: "{{ source_bucket_info.s3_keys }}"