---
- name: Run 'manage_vpc_peering' role
  module_defaults:
    group/aws: "{{ aws_role_credentials }}"

  block:
    - name: Include file
      ansible.builtin.include_tasks: "{{ vpc_peering_operation }}.yaml"
