---
- name: Check if the AMI already exists
  ec2_ami_info:
    filters:
      name: "{{ custom_ami_name }}"
  register: existing

- name: Create custom AMI
  block:
    - name: Delete existing AMI
      ec2_ami:
        name: "{{ existing.images.0.name }}"
        image_id: "{{ existing.images.0.image_id }}"
        wait: true
        state: absent
      when: existing.images | length > 0

    - name: Get source AMI id
      block:
        - name: Get source AMI image ID using filters
          ec2_ami_info:
            filters: "{{ source_ami_filters }}"
          register: images
          # very spammy
          no_log: true

        - fail:
            msg: "No AMI found using filters"
          when: images.images | length == 0

      when: source_ami_image_id is not defined

    - name: Define AMI id to create EC2 instance
      set_fact:
        source_ami_image_id: "{{ source_ami_image_id is defined \
                            | ternary(source_ami_image_id, \
                                images.images.0.image_id) }}"

    - vars:
        ec2_resource_prefix: "{{ custom_ami_name }}-prefix"
        ec2_ami_image_id: "{{ source_ami_image_id }}"

      block:
        - name: Create temporary file to store ssh private key
          tempfile:
            suffix: id_rsa
          register: private_key

        - include_tasks: tasks/create_ec2_resources.yaml
          vars:
            ec2_keypair_file: "{{ private_key.path }}"

        - name: Install required softwares and python modules
          block:
            - name: Install packages
              package:
                name: "{{ item }}"
                state: present
              with_items: "{{ custom_ami_packages }}"
          when: custom_ami_packages is defined
          become: true
          delegate_to: ec2

        - name: Create custom AMI from instance id
          ec2_ami:
            instance_id: "{{ ec2_instance_id }}"
            name: "{{ custom_ami_name }}"
            wait: true
            state: present

      always:
        - include_tasks: tasks/delete_ec2_resources.yaml

        - name: Delete temporary file
          file:
            path: "{{ private_key.path }}"
            state: absent
          ignore_errors: true

  when: (existing.images | length == 0) or (custom_ami_recreate_if_exists | bool)

- debug:
    msg: "Existing AMI found with name: '{{ custom_ami_name }}'"
  when:
    - existing.images | length > 0
    - not (custom_ami_recreate_if_exists | bool)
