---
- name: List existing AMI by name
  amazon.aws.ec2_ami_info:
    filters:
      name: "{{ custom_ami_name }}"
  register: customized_ami__existing_amis

- name: Delete AMI
  amazon.aws.ec2_ami:
    name: "{{ item.name }}"
    image_id: "{{ item.image_id }}"
    wait: true
    state: absent
  with_items: "{{ customized_ami__existing_amis.images }}"
  when:
    - customized_ami__existing_amis.images | length > 0
    - custom_ami_recreate_if_exists | bool
