---
- name: Get vpc information
  amazon.aws.ec2_vpc_net_info:
    filters:
      tag:Name: "{{ custom_ami_vpc_name }}"
  register: customized_ami__vpc

- name: Delete EC2 resources
  when: customized_ami__vpc.vpcs | length == 1
  block:
    - name: Set 'vpc_id' variable
      ansible.builtin.set_fact:
        customized_ami__vpc_id: "{{ customized_ami__vpc.vpcs.0.vpc_id }}"

    - name: Get EC2 instance info
      amazon.aws.ec2_instance_info:
        filters:
          vpc-id: "{{ customized_ami__vpc_id }}"
      register: customized_ami__instances

    - name: Delete EC2 instance
      amazon.aws.ec2_instance:
        instance_ids: "{{ customized_ami__instances.instances | map(attribute='instance_id') }}"
        wait: true
        state: terminated
      when: customized_ami__instances.instances | length > 0

    - name: Delete key pair to connect to the VM
      amazon.aws.ec2_key:
        name: "{{ custom_ami_key_name }}"
        state: absent

    - name: List Security group from VPC
      amazon.aws.ec2_security_group_info:
        filters:
          vpc-id: "{{ customized_ami__vpc_id }}"
          description: "{{ custom_ami_security_group_desc }}"
      register: customized_ami__security_groups

    - name: Delete security groups
      amazon.aws.ec2_security_group:
        state: absent
        group_id: "{{ item }}"
      with_items: "{{ customized_ami__security_groups.security_groups | map(attribute='group_id') | list }}"

    - name: List routes table from VPC
      amazon.aws.ec2_vpc_route_table_info:
        filters:
          vpc-id: "{{ customized_ami__vpc_id }}"
          association.main: false
      register: customized_ami__route_table

    - name: Delete VPC route table
      amazon.aws.ec2_vpc_route_table:
        route_table_id: "{{ item }}"
        vpc_id: "{{ customized_ami__vpc_id }}"
        lookup: id
        state: absent
      with_items: "{{ customized_ami__route_table.route_tables | map(attribute='id') | list }}"

    - name: Delete internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ customized_ami__vpc_id }}"
        state: absent

    - name: Delete subnets
      amazon.aws.ec2_vpc_subnet:
        cidr: "{{ custom_ami_subnet_cidr }}"
        state: absent
        vpc_id: "{{ customized_ami__vpc_id }}"

    - name: Delete VPC
      amazon.aws.ec2_vpc_net:
        vpc_id: "{{ customized_ami__vpc_id }}"
        state: absent
