---
# tasks file for roles/awsconfigremediation_enable_cloudtrail_encryption_with_kms

- fail:
    msg: "The ARN or name of the trail you want to update to be encrypted must be defined as awsconfigremediation_enable_cloudtrail_encryption_with_kms_trail_name"
  when: awsconfigremediation_enable_cloudtrail_encryption_with_kms_trail_name is not defined

- fail:
    msg: "The ARN, key ID, or the key alias of the of the customer managed key you want to use to encrypt the trail must be defined as awsconfigremediation_enable_cloudtrail_encryption_with_kms_kms_key_id"
  when: awsconfigremediation_enable_cloudtrail_encryption_with_kms_kms_key_id is not defined

- fail:
    msg: "The Amazon Resource Name (ARN) of the AWS Identity and Access Management (IAM) role that allows Systems Manager Automation to perform the actions on your behalf must be defined as awsconfigremediation_enable_cloudtrail_encryption_with_kms_automation_assume_role"
  when: awsconfigremediation_enable_cloudtrail_encryption_with_kms_automation_assume_role is not defined

- name: Gather information about the trail
  amazon.aws.cloudtrail_info:
    trail_names:
      - "{{ awsconfigremediation_enable_cloudtrail_encryption_with_kms_trail_name }}"
  register: __trail_info

- fail:
    msg: "The trail does not exist awsconfigremediation_enable_cloudtrail_encryption_with_kms_trail_name"
  when: __trail_info.trail_list | length == 0

- name: Gather information about the KMS key
  amazon.aws.kms_key_info:
    filters:
      "tag:Name": "{{ awsconfigremediation_enable_cloudtrail_encryption_with_kms_kms_key_id }}"
  register: __kms_key_info

- fail:
    msg: "The KMS key does not exist awsconfigremediation_enable_cloudtrail_encryption_with_kms_trail_name"
  when: __kms_key_info.kms_keys | length == 0

- set_fact:
    kms_key_arn: __kms_key_info.kms_keys.0.key_arn

- name: Enable encryption on the trail 
  amazon.aws.cloudtrail:
    state: present
    name: "{{ awsconfigremediation_enable_cloudtrail_encryption_with_kms_trail_name }}"
    kms_key_id: "{{ awsconfigremediation_enable_cloudtrail_encryption_with_kms_kms_key_id }}"
  register: __enable_encyption

- name: Verify that encryption has been enabled on the CloudTrail trail 
  amazon.aws.cloudtrail_info:
    trail_names:
      - "{{ awsconfigremediation_enable_cloudtrail_encryption_with_kms_trail_name }}"
  register: __verify_encryption

- assert:
    that:
      - __verify_encryption.trail_list.0.kms_key_id == "{{ awsconfigremediation_enable_cloudtrail_encryption_with_kms_kms_key_id }}"
    success_msg: "AWS CloudTrail trail has been successfully encrypted"
