---
argument_specs:
  main:
    short_description: A role to create or delete an EC2 instance with optional networking resources.
    description:
      - A role to create or delete an EC2 instance.
      - Can optionally attach security groups and associate an Elastic IP with the instance.
      - Supports custom configurations for instance settings including instance type, AMI, key pair, tags, VPC/subnet, and networking configurations.
    options:
      manage_ec2_instance_operation:
        description:
          - Whether to create or delete resources using the role.
        required: false
        type: str
        default: create
        choices: [create, delete]
      manage_ec2_instance_instance_name:
        description:
          - The name of the EC2 instance to be created.
        required: true
        type: str
      manage_ec2_instance_instance_type:
        description:
          - The instance type for the EC2 instance. Required when `manage_ec2_instance_operation` is `create`.
        required: false
        type: str
      manage_ec2_instance_ami_id:
        description:
          - The AMI ID for the EC2 instance. Required when `manage_ec2_instance_operation` is `create`.
        required: false
        type: str
      manage_ec2_instance_key_name:
        description:
          - The name of the key pair to use for SSH access to the EC2 instance. If the key does not exist, a key pair will be created with the name. If not provided, instance will not be accessible via SSH. If provided when `manage_ec2_instance_operation` is `delete`, the keypair will also be deleted.
        required: false
        type: str
      manage_ec2_instance_vpc_subnet_id:
        description:
          - The ID of the VPC subnet in which the instance will be launched. If not provided, instance will be created in the default subnet for the default VPC in the AWS region, if present.
        required: false
        type: str
      manage_ec2_instance_tags:
        description:
          - A dictionary of tags to assign to the EC2 instance.
        required: false
        type: dict
      manage_ec2_instance_wait_for_state:
        description:
          - Whether to wait for the EC2 instance to be in the running/terminated state before continuing.
        required: false
        default: true
        type: bool
      manage_ec2_instance_associate_security_groups:
        description:
          - List of security group names or IDs to associate with the EC2 instance.
        required: false
        type: list
        elements: str
      manage_ec2_instance_associate_eip:
        description:
          - Whether to create and associate an Elastic IP (EIP) with the EC2 instance.
        required: false
        default: false
        type: bool
      manage_ec2_instance_eip_tags:
        description:
          - Tags to assign to the Elastic IP.
        required: false
        type: dict
