---
- name: Webapp
  hosts: localhost
  gather_facts: false

  collections:
    - community.aws
    - amazon.aws

  vars_files:
    - vars/main.yaml

  tasks:
    - name: Fail when 'resource_prefix' is not defined
      ansible.builtin.fail:
        msg: resource prefix should be defined as resource_prefix
      when: resource_prefix is not defined

    - name: Run operation create/delete
      ansible.builtin.import_tasks: tasks/{{ operation }}.yaml

- name: Deploy resource from Bastion
  hosts: bastion
  gather_facts: false

  collections:
    - community.aws
    - amazon.aws

  module_defaults:
    group/aws:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      security_token: "{{ security_token | default(omit) }}"
      region: "{{ aws_region }}"

  vars_files:
    - vars/main.yaml

  tasks:
    - name: Deploy app
      ansible.builtin.import_tasks: tasks/deploy_app.yaml
