---
name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

'on':
  push:
    branches:
      - main
      - stable-*
  pull_request:
    branches:
      - main
      - stable-*

jobs:
  linters:
    uses: ansible-network/github_actions/.github/workflows/tox-linters.yml@main
  ansible-lint:
    uses: ansible-network/github_actions/.github/workflows/ansible-lint.yml@main
