---
name: Linters
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.8']
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Test with tox
        run: tox -e linters -vv

  ansible-lint:
    uses: ansible-network/github_actions/.github/workflows/ansible-lint.yml@main
