---
name: Linters
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

'on':
  push:
  pull_request:

jobs:
  linters:
    uses: ansible-network/github_actions/.github/workflows/tox-linters.yml@main
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ansible-network/github_actions/.github/actions/checkout_dependency@main

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6.16.2
